version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: latin-med-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: latin_med_terms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jamshid4884
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: latin-med-api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app

volumes:
  postgres_data:
